// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Task.Data;

namespace Task.Migrations
{
    [DbContext(typeof(PatientContext))]
    [Migration("20200104082635_SeedPatientTable")]
    partial class SeedPatientTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Task.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Diagnosis = "pneumonia",
                            Name = "Mark"
                        },
                        new
                        {
                            Id = 2,
                            Diagnosis = "tuberculosis",
                            Name = "Hamilton"
                        },
                        new
                        {
                            Id = 3,
                            Diagnosis = "blood cancer",
                            Name = "James"
                        },
                        new
                        {
                            Id = 4,
                            Diagnosis = "schizophrenia",
                            Name = "Alexceander"
                        },
                        new
                        {
                            Id = 5,
                            Diagnosis = "pneumonia",
                            Name = "Arthur"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
